name: vayroll
description: A new Flutter project.


publish_to: 'none'
version: 1.1.11+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.0
  http_retry: ^0.2.0
  flutter_svg: ^2.0.5
  pin_code_fields: ^8.0.1
  provider: ^6.0.5
  permission_handler: ^10.4.3
  local_auth: ^2.1.6
  shared_preferences: ^2.0.6
  firebase_remote_config: ^4.2.4
  device_info_plus: ^9.0.2
  url_launcher: ^6.0.3
  android_intent: ^2.0.0
  dio: ^5.3.0
  firebase_core: any
  firebase_messaging: ^14.6.5
  firebase_crashlytics: ^3.3.4
  firebase_analytics: ^10.4.4
  firebase_performance: ^0.9.2+4
  universal_platform:
  email_validator: ^2.0.1
  encrypt: ^5.0.0
  table_calendar: ^3.0.8
  jiffy: ^6.2.1
  equatable: ^2.0.2
  sliver_tools: ^0.2.2
  webview_flutter: ^4.0.7
  infinite_scroll_pagination: ^3.1.0
  file_picker: ^5.3.1
  pdf_render: any
  month_picker_dialog: ^2.0.2
  path_provider: ^2.0.2
  open_file_plus: ^3.4.1
  percent_indicator: ^4.2.3
  geolocator: ^9.0.2
  share_plus: ^7.0.2
  fl_chart: ^0.63.0
  google_ml_kit: ^0.16.1
  image_picker: ^1.0.1
  confetti: ^0.7.0
  dropdown_search: ^5.0.6
  flutter_local_notifications: ^15.1.0+1
  assorted_layout_widgets: ^8.0.4
  dotted_line: ^3.0.0
  showcaseview: ^2.0.3
  synchronized: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  country_code_picker: ^3.0.0
  screenshot: ^2.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  auto_size_text: ^3.0.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/pictures/logos/
    - assets/pictures/images/
    - assets/pictures/icons/
    - assets/pictures/gif/

  fonts:
    - family: Brandon
      fonts:
        - asset: assets/fonts/Brandon_thin.otf
          weight: 100
        - asset: assets/fonts/Brandon_thin_it.otf
          weight: 100
          style: italic
        - asset: assets/fonts/Brandon_light.otf
          weight: 300
        - asset: assets/fonts/Brandon_light_it.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Brandon_reg.otf
          weight: 400
        - asset: assets/fonts/Brandon_reg_it.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Brandon_med.otf
          weight: 500
        - asset: assets/fonts/Brandon_med_it.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Brandon_bld.otf
          weight: 700
        - asset: assets/fonts/Brandon_bld_it.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Brandon_blk.otf
          weight: 900
        - asset: assets/fonts/Brandon_blk_it.otf
          weight: 900
          style: italic
    - family: HKGrotesk
      fonts:
        - asset: assets/fonts/HKGrotesk-Regular.otf
        - asset: assets/fonts/HKGrotesk-Medium.otf
          weight: 500
        - asset: assets/fonts/HKGrotesk-SemiBold.otf
          weight: 600
        - asset: assets/fonts/HKGrotesk-Bold.otf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.otf
