// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpSEEOph-bxfDDwF6ycKr4W9qQnWlEOVg',
    appId: '1:560953317442:android:0fb405123a982b175bb5db',
    messagingSenderId: '560953317442',
    projectId: 'vayroll',
    storageBucket: 'vayroll.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0nvYsS0wjcl8LLOOIwR5dieSMbn0Jj48',
    appId: '1:560953317442:ios:ab9019811c6ba6675bb5db',
    messagingSenderId: '560953317442',
    projectId: 'vayroll',
    storageBucket: 'vayroll.appspot.com',
    androidClientId: '560953317442-pmq8rl1mlb497caa6lm0gun3c0hnln2d.apps.googleusercontent.com',
    iosClientId: '560953317442-c9clv9s8srvk5ikfel5en1pd576a6d2l.apps.googleusercontent.com',
    iosBundleId: 'com.transskills.vayroll',
  );
}
